name: Lighthouse CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno install --allow-scripts=npm:dprint,npm:@remix-run/style,npm:@remix-run/events,npm:@remix-run/dom
      - run: deno run -A npm:@lhci/cli@0.15.x autorun
