name: Lighthouse CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno run --node-modules-dir=auto -A npm:@lhci/cli@0.15.x autorun
